[build-system]
requires = ["setuptools>=60", "setuptools-scm>=7.1.0"]
build-backend = "setuptools.build_meta"

[project]
name = "django-import-export"
authors = [
    {name = "Bojan Mihelač", email = "djangoimportexport@gmail.com"},
]
maintainers = [
    {name = "Matthew Hegarty", email = "djangoimportexport@gmail.com"},
]
description = "Django application and library for importing and exporting data with included admin integration."
keywords = ["django", "import", "export"]
license = {file = "LICENSE"}
requires-python = ">=3.9"
readme = "README.rst"
dynamic = ["version"]
classifiers = [
    "Framework :: Django",
    "Framework :: Django :: 4.2",
    "Framework :: Django :: 5.0",
    "Framework :: Django :: 5.1",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Software Development",
]

dependencies = [
    "diff-match-patch==20241021",
    "Django>=4.2",
    "tablib==3.7.0"
]

[project.optional-dependencies]
all = [
    "tablib[all]"
]
cli = ["tablib[cli]"]
ods = ["tablib[ods]"]
pandas = ["tablib[pandas]"]
xls = ["tablib[xls]"]
xlsx = ["tablib[xlsx]"]
yaml = ["tablib[yaml]"]
docs = [
    "sphinx==8.1.3",
    "sphinx-rtd-theme==3.0.1"
]
tests = [
    "psycopg2-binary==2.9.10",
    "mysqlclient==2.2.5",
    "chardet==5.2.0",
    "pytz==2024.2",
    "memory-profiler==0.61.0",
    "django-extensions==3.2.3",
    "coverage==7.6.4",
    "tablib[all]>=3.7.0",
    "setuptools-scm==8.1.0",
]

[project.urls]
Documentation = "https://django-import-export.readthedocs.io/en/stable/"
Repository = "https://github.com/django-import-export/django-import-export"
Changelog = "https://github.com/django-import-export/django-import-export/blob/main/docs/changelog.rst"

[tool.setuptools]
platforms = ["OS Independent"]
license-files = ["LICENSE", "AUTHORS"]

[tool.setuptools_scm]
write_to = "import_export/_version.py"
local_scheme = "no-local-version"

[tool.isort]
profile = "black"

[tool.tox]
legacy_tox_ini = """
    [tox]
    min_version = 4.0
    envlist =
        {py39}-{django42}
        {py310,py311,py312,py313}-{django42,django50,django51,djangomain}
        py313-djangomain-tablibdev

    [testenv]
    setenv = PYTHONPATH = {toxinidir}/tests
    commands =
        python \
            -W error::DeprecationWarning \
            -W error::PendingDeprecationWarning \
            -m coverage run \
            ./tests/manage.py test core \
            {posargs}
    deps =
        tablibdev: -egit+https://github.com/jazzband/tablib.git@master#egg=tablib
        django42: Django>=4.2,<5.0
        django50: Django>=5.0,<5.1
        django51: Django>=5.1,<5.2
        djangomain: https://github.com/django/django/archive/main.tar.gz
        .[tests]

    # if postgres / mysql environment variables exist, we can go ahead and run db specific tests
    passenv =
        IMPORT_EXPORT_POSTGRESQL_USER
        IMPORT_EXPORT_POSTGRESQL_PASSWORD
        IMPORT_EXPORT_POSTGRESQL_PORT
        IMPORT_EXPORT_MYSQL_USER
        IMPORT_EXPORT_MYSQL_PASSWORD
        IMPORT_EXPORT_MYSQL_PORT
        IMPORT_EXPORT_TEST_TYPE
"""